Metadata URI
open-dollar/od-seaport-zone pull request #13
Opened 2024-05-21 22:45 UTC by daopunk

closes #10

2024-05-22 00:40 UTC, pi0neerpat requested changes
please re-request when ready

2024-05-23 02:16 UTC, daopunk commented
<img width="388" alt="Screenshot 2024-05-22 at 7 16 30 PM" src="https://github.com/open-dollar/od-seaport-zone/assets/50965054/422b5906-6e2e-4904-bd9d-b3095c52ba68">

2024-05-23 02:43 UTC, daopunk commented
@pi0neerpat Sol version is broken
![Screenshot 2024-05-22 at 7 43 05 PM](https://github.com/open-dollar/od-seaport-zone/assets/50965054/d1abc050-4c2d-4ea7-a68d-cbd218ea0a0b)

2024-05-23 23:52 UTC, pi0neerpat approved these changes

2024-05-24 00:15 UTC, merged