Solidity natSpec
open-dollar/od-seaport-zone pull request #20
Opened 2024-05-29 19:03 UTC by daopunk

primary function order:
1. constructor
2. receive function (if exists)
3. fallback function (if exists)
4. external
5. public
6. internal
7. private

secondary considerations:
1. view
2. pure

https://docs.soliditylang.org/en/v0.8.26/natspec-format.html
https://docs.soliditylang.org/en/v0.8.26/style-guide.html

2024-05-29 21:43 UTC, pi0neerpat commented
Still a wip? I don't see any new code comments

2024-05-29 21:43 UTC, pi0neerpat requested changes
Waiting on comments

2024-05-29 23:04 UTC, daopunk commented
> Waiting on comments

what comments? this is not a work in progress. it's ready

2024-05-30 19:48 UTC, pi0neerpat approved these changes

2024-05-30 19:51 UTC, merged